const { name: ROOT_PACKAGE_NAME } = require('../package.json');

const STAGE = process.env.NODE_ENV;

const {
  AWS_REGION,
  AWS_ACCOUNT_ID,
  STACK_NAME = ROOT_PACKAGE_NAME,
  CONFIGS_TABLE = `${ROOT_PACKAGE_NAME}-${STAGE}-configs`,
  DOCTORS_TABLE = `${ROOT_PACKAGE_NAME}-${STAGE}-doctors`,
  PATIENTS_TABLE = `${ROOT_PACKAGE_NAME}-${STAGE}-patients`,
  FACILITIES_TABLE = `${ROOT_PACKAGE_NAME}-${STAGE}-facilities`,
  GOOGLE_DISTANCES_MATRIX_API_KEY = '',
  GOOGLE_APPLICATION_CREDENTIALS = '',
  DOCTOR_INACTIVITY_TIMEOUT_IN_MINUTES = 33,
} = process.env;

module.exports = {
  AWS_REGION,
  AWS_ACCOUNT_ID,
  STAGE,
  APP_NAME: ROOT_PACKAGE_NAME,
  STACK_NAME,
  ROOT_PACKAGE_NAME,
  CONFIGS_TABLE,
  DOCTORS_TABLE,
  PATIENTS_TABLE,
  FACILITIES_TABLE,
  GOOGLE_DISTANCES_MATRIX_API_KEY,
  GOOGLE_APPLICATION_CREDENTIALS,
  DOCTOR_INACTIVITY_TIMEOUT_IN_MINUTES,
};
