const ROOT_PACKAGE_NAME = 'barracao-digital'
const STAGE = process.env.NODE_ENV

const {
  APP_URL,
  AWS_REGION,
  AWS_ACCOUNT_ID,
  STACK_NAME = ROOT_PACKAGE_NAME,
  GOOGLE_DISTANCES_MATRIX_API_KEY = '',
  GOOGLE_APPLICATION_CREDENTIALS = '',
  OPENTOK_API_KEY = '',
  OPENTOK_API_SECRET = '',
  CONFIGS_TABLE = `${ROOT_PACKAGE_NAME}-${STAGE}-configs-table`,
  DOCTORS_TABLE = `${ROOT_PACKAGE_NAME}-${STAGE}-doctors-table`,
  PATIENTS_TABLE = `${ROOT_PACKAGE_NAME}-${STAGE}-patients-table`,
  FACILITIES_TABLE = `${ROOT_PACKAGE_NAME}-${STAGE}-facilities-table`,
  DOCTOR_INACTIVITY_TIMEOUT_IN_MINUTES = 33,
  TELEGRAM_TOKEN = '',
} = process.env

export {
  APP_URL,
  AWS_REGION,
  AWS_ACCOUNT_ID,
  STAGE,
  ROOT_PACKAGE_NAME as APP_NAME,
  STACK_NAME,
  ROOT_PACKAGE_NAME,
  GOOGLE_DISTANCES_MATRIX_API_KEY,
  GOOGLE_APPLICATION_CREDENTIALS,
  OPENTOK_API_KEY,
  OPENTOK_API_SECRET,
  CONFIGS_TABLE,
  DOCTORS_TABLE,
  PATIENTS_TABLE,
  FACILITIES_TABLE,
  DOCTOR_INACTIVITY_TIMEOUT_IN_MINUTES,
  TELEGRAM_TOKEN,
}
