const {
  NODE_ENV,
  VUE_APP_BASE_URL = '',
  VUE_APP_API_URL,
  VUE_APP_FIREBASE_CONFIG,
} = process.env;

const API_URL = `${VUE_APP_API_URL}/${NODE_ENV}`;

export {
  NODE_ENV,
  API_URL,
  VUE_APP_BASE_URL as BASE_URL,
  VUE_APP_FIREBASE_CONFIG as FIREBASE_CONFIG,
};
